# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "CS373 Spring 2016: Kristine Domingo"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Homepage"
    href:           "//kristinedomingo.com"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
